### ISSUE TITLE
Uspješna registracija korisnika- header?

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#107]
http://prntscr.com/bz934j
Ista stvar kao i kod tvrkte

**Comment by gjorgic** [comment]
- [ ] Kreiraj branch `header-menu-controll`
ovdje je potrebno dodati property `visible` u state i akciju s kojom se može mjenjati taj podatak bez da se utječe na iteme u izborniku;

- [ ] Kreiraj branch `without-header-menu-base-class` iz `header-menu-controll`
@nikolakrivokapic Potrebno je u `src/routes` kreirati klasu WithoutHeaderMenu koja proširuje `React.Component` i ima metode `componentWillMount` & `componentWillUnmount`

[componentWillMount](#) - pozvati funkciju za sakjrivanje izbornika
[componentWillUnmount](#) - pozvati funkciju za ponovno pokazivanje izbornika

- [ ] Kreiraj branch `implement-without-header-menu` iz `without-header-menu-base-class`
potrebno je integrirati prethodno napravljenu klasu na page gdje se dodaju interesi i istestirati tako da se registriraš i odeš aktivirati svoj acc; ako je sve dobro napravljeno onda se izbornik nebi trebao prikazati

**Comment by gjorgic** [comment]
rješeno
