### ISSUE TITLE
Verifikacija- button "Povratak" trenutno vraća na naslovnicu

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#42]
Možemo li napraviti da "Povratak" vrati na prethodni page odnosno page za registraciju?

http://prntscr.com/bt61i1

**Comment by gjorgic** [comment]
Može

**Comment by gjorgic** [comment]
Ovdje je potrebno srediti i layout templatea za registraciju; treba se ukloniti klasa sa taga `section` i tag `section` se treba promjeniti u `div`
Taj kontent se nalazi unutar Komponente RegisterLayout ili nešto tako...

**Znači ako netko ovo ne može fiksati bez da mjenja css onda nije na dobrom putu**

**Comment by gjorgic** [comment]
- [x] Back to register page

- [ ] Check layout on thankyu screen

**Comment by gjorgic** [comment]
Na slici je raspadnut layout međutim nisam to uspiuo replicirtati tako da zatvaram ovo
