### ISSUE TITLE
Registracija tvrtke/škole - krivi tekst

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#46]
http://prntscr.com/bv6hsg

Ovaj tekst treba ići kod registracije korisnika, a
**kod registracije tvrtke se povlaći random tekst iz baze**

**Comment by gjorgic** [comment]
treba kreirati **poseban branch sa prefixom `46registracija-text`**

Što se tiče teksta koji se povlači iz baze; taj dio za sad ostavi, tj. na njegovo mjesto stavi neki lorem ili prepiši neku motivacijsku poruku iz invisiona sa login popup-a

## Ovo odraditi na Beckend aplikaciji
kreirati branch iz `dev`-a `motivation-message`

Potrebno je Backend aplikaciji predviditi tablicu sa motivacijskim porukama ina će imati
**id** _int(11)_
**author** _string (100)_
**message** _text_
**status** _text (25)_
**group** _string (25)_
**created_at** _timestamp_
**updated_at** _datetime_
**deleted_at** _datetime_

treba se napraviti ruta za izlistavanje

|metoda|path|desc|
|---|---|---|
|[GET](#)|_/motivation-message/list_| list all|
|[POST](#)|_/motivation-message_|create|
|[POST](#)|_/motivation-message/:id_|edit|
|[GET](#)|_/motivation-message/:id_|show|
|[POST](#)|_/motivation-message/:id_|delete|

***
Molim da se promjene komitaju po svakom fajlu na oba projekta

**Comment by gjorgic** [comment]
kreirat cu issue u backend app
