### ISSUE TITLE
Registracija tvrtke - nedostaju zvjezdice za obavezna polja

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#47]
Ovo je sad na devu: http://prntscr.com/bv6k31

Treba biiti po [dizajnu ](https://projects.invisionapp.com/d/main#/console/6795853/147267471/preview)
- sva polja su obavezna osim "Broj zaposlenih"

**Comment by gjorgic** [comment]
treba ju se staviti zvjezdice
