### ISSUE TITLE
Registracija tvrtke/škole - error kad korisnik već postoji u bazi

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#48]
"Poruka neka glasi: 
## # Korisnik s navedenom e-mail adresom već postoji"

Trenutno je [ovako](http://prntscr.com/bt5z48)

**Comment by gjorgic** [comment]
Ova poruka se mora dodati u Backend aplikaciju (laravel)

**Comment by nikolakrivokapic** [comment]
pušo sam novi branch na backend-u i napravio pull request
