### ISSUE TITLE
Uspješna registracija- krivi tekst na buttonu

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#50]
[Ovaj ](http://prntscr.com/bv6s2n) button 

### ## Treba pisati: "Dodaj interese"

**Comment by gjorgic** [comment]
Prema posljednjem dogovoru sa Ivanom M. ovaj issue se može zatvoriti;

dakle ignorirati ga

**Comment by plavatvornica** [comment]
Tako je
