### ISSUE TITLE
Naslovnica- zadnja sekcija (tvrke i škole)

### ISSUE THREAD

**Issue by plavatvornica** [plavatvornica/cc#67]
Button "Objavi natječaj" ne vodi nikud- mora voditi na registraciju tvrtke/škole što [ovdje ](http://prntscr.com/bxrbja) i piše ali ne vodi na taj page

**Comment by gjorgic** [comment]
Uradi branch `64home-fix`

i u njemu odradi ovaj task i task

#68 

Vezani task
- [ ] #68

**Comment by erklat** [comment]
#36 sam iskomentirao dolje pa reci kako ćemo.
